### ISSUE TITLE
Install-debian.sh is producing array of errors. Not working on fresh OS.

### ISSUE THREAD

**Issue by molekm** [ONLYOFFICE/Docker-CommunityServer#163]
Fresh Hetzner Ubuntu 18
Installing ONLYOFFICE Groups using script
STEP 1: Download the installation script file
Execute the following command:

wget https://download.onlyoffice.com/install/install-Debian.sh
STEP 2: Install ONLYOFFICE Groups
Run the script specifying the -it GROUPS parameter:

bash install-Debian.sh -it GROUPS

leads to 

`WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting radicale==3.0.5
  Downloading Radicale-3.0.5-py3-none-any.whl (121 kB)
     |████████████████████████████████| 121 kB 8.4 MB/s
Collecting defusedxml
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting vobject>=0.9.6
  Downloading vobject-0.9.6.1.tar.gz (58 kB)
     |████████████████████████████████| 58 kB 10.9 MB/s
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0ou64ljr/vobject_e64300faaa0b47e3ad873e7919388b1e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0ou64ljr/vobject_e64300faaa0b47e3ad873e7919388b1e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-lg4boh1p
       cwd: /tmp/pip-install-0ou64ljr/vobject_e64300faaa0b47e3ad873e7919388b1e/
  Complete output (3 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named 'setuptools'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/da/ce/27c48c0e39cc69ffe7f6e3751734f6073539bf18a0cfe564e973a3709a52/vobject-0.9.6.1.tar.gz#sha256=96512aec74b90abb71f6b53898dd7fe47300cc940104c4f79148f0671f790101 (from https://pypi.org/simple/vobject/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading vobject-0.9.6.tar.gz (58 kB)
     |████████████████████████████████| 58 kB 12.6 MB/s
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0ou64ljr/vobject_d47037e8763d4132b0c656f88fc1a511/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0ou64ljr/vobject_d47037e8763d4132b0c656f88fc1a511/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-b5gq3bzi
       cwd: /tmp/pip-install-0ou64ljr/vobject_d47037e8763d4132b0c656f88fc1a511/
  Complete output (3 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named 'setuptools'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/59/18/717cb744b769ffed2fc97f952e75c16781932861806ae82995540458677a/vobject-0.9.6.tar.gz#sha256=cd9ede4363f83c06ba8d8f1541c736efa5c46f9a431430002b2f84f4f4e674d8 (from https://pypi.org/simple/vobject/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement vobject>=0.9.6 (from radicale) (from versions: 0.2.3, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.5.0, 0.6.6, 0.8.1rc0, 0.8.2, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.4.1, 0.9.5, 0.9.6, 0.9.6.1)
ERROR: No matching distribution found for vobject>=0.9.6
dpkg: error processing package onlyoffice-communityserver (--configure):
 installed onlyoffice-communityserver package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 onlyoffice-communityserver
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

**Comment by Carazyda** [comment]
Hello @molekm Sorry, but we cant reproduce your problem. Try to install setuptools `sudo apt-get install python3-setuptools` and rerun our installation script. Or try use more newest version of Ubuntu.

**Comment by molekm** [comment]
> 

Install fresh Ubuntu 18.04 and follow the steps. Did you do it? 

I am replicating that EVERY SINGLE time.

**Comment by molekm** [comment]
> Hello @molekm Sorry, but we cant reproduce your problem. Try to install setuptools `sudo apt-get install python3-setuptools` and rerun our installation script. Or try use more newest version of Ubuntu.

Install fresh ubuntu 18 server, and follow the steps.

I've tried 3 times and it was always the same issue. 

If it doesn't work on 18 then simply remove it from requirements.  I won't be testing any other OS as we are using Ubuntu 18 on all hundreds of machines. For now machine with OnlyOffice was killed and awaiting the bug fix.

**Comment by molekm** [comment]
> Hello @molekm Sorry, but we cant reproduce your problem. Try to install setuptools `sudo apt-get install python3-setuptools` and rerun our installation script. Or try use more newest version of Ubuntu.

Ubuntu 22 gives this error (non docker install as this is a dedicated machine)

`W: http://nginx.org/packages/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: http://download.onlyoffice.com/repo/debian/dists/squeeze/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://artifacts.elastic.co/packages/7.x/apt/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://d2nlctn12v279m.cloudfront.net/repo/mono/ubuntu/dists/focal/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://deb.nodesource.com/node_12.x/dists/focal/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: https://download.mono-project.com/repo/ubuntu/dists/stable-focal/snapshots/6.8.0.123/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: Conflicting distribution: https://download.mono-project.com/repo/ubuntu stable-focal/snapshots/6.8.0.123 InRelease (expected stable-focal/snapshots/6.8.0.123 but got focal)
/dev/fd/63: line 138: snap: command not found
`

**Comment by Carazyda** [comment]
The installation works on Ubuntu 18.04. We tested it on DigitalOcean and AWS EC2. Some cloud services may modify the original OS image. Sorry, but we cannot support all cloud services. We will try to check Hetzner soon.


> line 138: snap: command not found

It seems this image of Ubuntu 22.04 does not have `snap` installed. Please check it and installed, before running our script.

**Comment by Carazyda** [comment]
Yes, you're right, we're having trouble installing on Hetzner Cloud (bug 58609 on our private bugtracker). We will try to fix this as soon as possible.
