### ISSUE TITLE
upgrading onlyoffice with larger version change

### ISSUE THREAD

**Issue by jiayouchongmingniao** [ONLYOFFICE/Docker-CommunityServer#176]
Dear support,
would you please guide me upgrading communityserver from 11.5.4.1582 to 12.1.0.1760 ？

so far i know

mysql from 5.7.36  -> 8.0.29
new elasticsearch docker ， 7.16.3

any suggestion？many thanks！

**Comment by Carazyda** [comment]
Hello @jiayouchongmingniao how did you install Onlyoffice Workspace? You can update the version from Control Panel, Update tab.

We don't recommend updating the Mysql version, its may crash the database.

**Comment by jiayouchongmingniao** [comment]
![1671073020533](https://user-images.githubusercontent.com/55178588/207761889-2cc6df3d-b6f3-4bea-973e-f2275327eca9.png)

**Comment by jiayouchongmingniao** [comment]
always with cycle，no ending

**Comment by jiayouchongmingniao** [comment]
![1671073182610](https://user-images.githubusercontent.com/55178588/207762229-adf48d14-da73-4266-8040-5e53f8146494.png)

**Comment by jiayouchongmingniao** [comment]
finally with this

**Comment by jiayouchongmingniao** [comment]
![1671073265360](https://user-images.githubusercontent.com/55178588/207762395-89333371-ad25-4dd8-857c-1ea14636c1a9.png)

**Comment by jiayouchongmingniao** [comment]
current index as above
upgrading is mainly for global search，latest version support Chinese keyword
thanks for your kind help and great support ！

**Comment by Carazyda** [comment]
Please check the console and network for errors in your browser's developer tools. Also check web.controlpanel.log for errors.

Make sure you have the latest version of docker installed.

**Comment by jiayouchongmingniao** [comment]
[root@localhost ~]# docker version
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275
 Built:             Tue Dec  1 19:14:24 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275
  Built:            Tue Dec  1 19:21:08 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by jiayouchongmingniao** [comment]
root@d83bbc30d7f1:/# find / -name web.control*log
/var/log/onlyoffice/web.controlpanel.12-11.log
root@d83bbc30d7f1:/# pwd
/
root@d83bbc30d7f1:/# cat /var/log/onlyoffice/web.controlpanel.12-11.log
2022-12-11 11:23:32 - error: http://onlyoffice-community-server/api/2.0/people/@self.json
2022-12-11 11:23:32 - error: http://onlyoffice-community-server/api/2.0/settings/companywhitelabel.json
2022-12-11 11:23:32 - error: http://onlyoffice-community-server/api/2.0/settings/controlpanel.json
2022-12-11 11:23:33 - error: http://onlyoffice-community-server/api/2.0/portal.json
root@d83bbc30d7f1:/#

**Comment by Carazyda** [comment]
This is too old version. Please try updating docker and check the update tab.

**Comment by jiayouchongmingniao** [comment]
after upgrading docker 

Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:30:24 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:28:33 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

![1671288207157](https://user-images.githubusercontent.com/55178588/208247451-704061a6-b86c-485d-9c8f-70c963b56e94.png)

**Comment by jiayouchongmingniao** [comment]
![1671288366561](https://user-images.githubusercontent.com/55178588/208247517-e21b4a5c-70c1-4811-9582-9d537f4079c9.png)

**Comment by Carazyda** [comment]
Were you able to update the components? Looking at the update tab, this is so. To remove the error in editors - you need to configure JWT. To do this, in the CommunityServer config `/var/www/onlyoffice/WebStudio/web.appsettings.config`, you need to register similar values secret and header of  the document server config `/etc/onlyoffice/documentserver/local.json`. (all configs are in the docker containers)

**Comment by jiayouchongmingniao** [comment]
![1671325131011](https://user-images.githubusercontent.com/55178588/208271989-75b52f43-2c3d-4f32-b3fc-1fae5c54e52a.png)

**Comment by jiayouchongmingniao** [comment]
![1671325201485(1)](https://user-images.githubusercontent.com/55178588/208272010-52177dab-4fe4-46a0-b9a5-3321b41586aa.png)

would you kindly give a setting example ？

**Comment by jiayouchongmingniao** [comment]
any keyword？ keep same is enough？

**Comment by jiayouchongmingniao** [comment]
after setting with document server 
JWT_ENABLED=true 
JWT_SECRET=jwt_secret 
JWT_HEADER=AuthorizationJwt 

and  community server "/var/www/onlyoffice/WebStudio/web.appsettings.config"
  <add key="files.docservice.secret" value="jwt_secret" />
  <add key="files.docservice.secret.header" value="AuthorizationJwt" />

new issue with "download error"

/var/log/onlyoffice/documentserver/converter/out.log

[2022-12-18T02:28:59.104] [ERROR] [localhost] [qj57QBw3Z2MwVxthVSZ6k_cUCPfPZ7_8XullwhVoRUQ_] [dfba14c4-f9a9-47f1-a5cc-7db96fef43e3] nodeJS - error downloadFile:url=http://onlyoffice-community-server:80/Products/Files/HttpHandlers/filehandler.ashx?action=stream&fileid=2661&stream_auth=409026536743.21UGRUCPE94UIUAC1M3PNNGPEIBJMONEDW0R6SFJGCW&X-REWRITER-URL=http%3a%2f%2f10.139.55.122%3a80;attempt=2;code:undefined;connect:undefined Error: Error response: statusCode:500; headers:{"server":"nginx/1.22.0","date":"Sun, 18 Dec 2022 02:28:59 GMT","content-type":"application/vnd.openxmlformats-officedocument.wordprocessingml.document","content-length":"14","connection":"keep-alive","content-disposition":"attachment; filename=\"åå¸å¼å­å¨ç³»ç»-CEPHè½åæåé¡¹ç®.docx\"; filename*=UTF-8''%E5%88%86%E5%B8%83%E5%BC%8F%E5%AD%98%E5%82%A8%E7%B3%BB%E7%BB%9F-CEPH%E8%83%BD%E5%8A%9B%E6%8F%90%E5%8D%87%E9%A1%B9%E7%9B%AE.docx","x-aspnet-version":"4.0.30319","cache-control":"private"};
    at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
    at Socket.socketOnData (_http_client.js:515:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[2022-12-18T02:29:00.122] [ERROR] [localhost] [qj57QBw3Z2MwVxthVSZ6k_cUCPfPZ7_8XullwhVoRUQ_] [dfba14c4-f9a9-47f1-a5cc-7db96fef43e3] nodeJS - error downloadFile:url=http://onlyoffice-community-server:80/Products/Files/HttpHandlers/filehandler.ashx?action=stream&fileid=2661&stream_auth=409026536743.21UGRUCPE94UIUAC1M3PNNGPEIBJMONEDW0R6SFJGCW&X-REWRITER-URL=http%3a%2f%2f10.139.55.122%3a80;attempt=3;code:undefined;connect:undefined Error: Error response: statusCode:500; headers:{"server":"nginx/1.22.0","date":"Sun, 18 Dec 2022 02:29:00 GMT","content-type":"application/vnd.openxmlformats-officedocument.wordprocessingml.document","content-length":"14","connection":"keep-alive","content-disposition":"attachment; filename=\"åå¸å¼å­å¨ç³»ç»-CEPHè½åæåé¡¹ç®.docx\"; filename*=UTF-8''%E5%88%86%E5%B8%83%E5%BC%8F%E5%AD%98%E5%82%A8%E7%B3%BB%E7%BB%9F-CEPH%E8%83%BD%E5%8A%9B%E6%8F%90%E5%8D%87%E9%A1%B9%E7%9B%AE.docx","x-aspnet-version":"4.0.30319","cache-control":"private"};
    at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
    at Socket.socketOnData (_http_client.js:515:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

**Comment by jiayouchongmingniao** [comment]
![1671331352066](https://user-images.githubusercontent.com/55178588/208278794-b096608f-b6fd-43c8-8d07-80d747996fe0.png)

**Comment by jiayouchongmingniao** [comment]
![1671331433226](https://user-images.githubusercontent.com/55178588/208278838-3891d274-cafe-49ed-82fc-48b0c5a77ae7.png)

**Comment by jiayouchongmingniao** [comment]
fs secretString related? 
no suitable location in  community server  /var/www/onlyoffice/WebStudio/web.appsettings.config

**Comment by jiayouchongmingniao** [comment]
update finished。many thanks for [Carazyda](https://github.com/Carazyda) great help ！

**Comment by jiayouchongmingniao** [comment]
![1671367938767](https://user-images.githubusercontent.com/55178588/208299422-9648db37-be70-41c7-9544-1489930cf493.png)

**Comment by Carazyda** [comment]
> https://github.com/ONLYOFFICE/Docker-CommunityServer/issues/176#issuecomment-1356640121

Is this error still there? Please try downloading the files in the Documents module. And try resaving the Document Service in the portal settings. Also check web.files.log for errors.

**Comment by jiayouchongmingniao** [comment]
have solved,  many thanks again !
